#ifndef STALLION_LIBC_STALLION_H
#define STALLION_LIBC_STALLION_H
#define STALLION_OS

#define STALLION_SYSCALL_EXIT 1
#define STALLION_SYSCALL_DECLARE_ATTRIBUTES 2
#define STALLION_SYSCALL_REQUEST_PERMISSIONS 3
#define STALLION_SYSCALL_GET_PID 4
#define STALLION_SYSCALL_CLOSE 5
#define STALLION_SYSCALL_ENVIRON 6
#define STALLION_SYSCALL_EXECVE 6
#define STALLION_SYSCALL_FORK 7
#define STALLION_SYSCALL_FSTAT 8
#define STALLION_SYSCALL_ISATTY 9
#define STALLION_SYSCALL_SEND_SIGNAL 10
#define STALLION_SYSCALL_LINK 11
#define STALLION_SYSCALL_LSEEK 12
#define STALLION_SYSCALL_OPEN 13
#define STALLION_SYSCALL_READ 14
#define STALLION_SYSCALL_SBRK 15
#define STALLION_SYSCALL_STAT 16
#define STALLION_SYSCALL_TIMES 17
#define STALLION_SYSCALL_UNLINK 18
#define STALLION_SYSCALL_WAIT 19
#define STALLION_SYSCALL_WRITE 20

#define STALLION_ATTRIBUTE_FILESYSTEM 1

#define STALLION_PERMISSION_SERIAL_READ 1
#define STALLION_PERMISSION_SERIAL_WRITE 2

#define STALLION_RESULT_FAIL 0
#define STALLION_RESULT_OK 1

#ifdef __ASSEMBLY__
#else
#include <stdint.h>

#if __STDC_VERSION__ >= 201112L
#define STALLION_NORETURN _Noreturn
#else
#ifdef __GNUC__
#define STALLION_NORETURN __attribute__((noreturn))
#else
#define STALLION_NORETURN
#endif
#endif

STALLION_NORETURN void stallion_syscall_exit(uint32_t exit_code);
int32_t stallion_syscall_declare_attributes(uint32_t attributes);
int32_t stallion_syscall_request_permissions(uint32_t permissions);
int32_t stallion_syscall_get_pid();

#endif

#endif